Repository MyChore/MyChore-Server, pull requests merged in 2023-08, with the labels that each got.

#16 #6 feat: 닉네임 중복 체크 API 생성
  src/main/java/com/mychore/mychore_server/controller/UserController.java
  src/main/java/com/mychore/mychore_server/service/UserService.java
Labels: 🏡feature

#17 #6 feat: 프로필 조회 API 생성
  src/main/java/com/mychore/mychore_server/controller/UserController.java
  src/main/java/com/mychore/mychore_server/dto/user/UserAssembler.java
  src/main/java/com/mychore/mychore_server/dto/user/response/GetProfileRes.java
  src/main/java/com/mychore/mychore_server/service/UserService.java
Labels: 🏡feature

#13 #9 집안일 API 구현
  src/main/java/com/mychore/mychore_server/controller/ChoreController.java
  src/main/java/com/mychore/mychore_server/dto/chore/ChoreAssembler.java
  src/main/java/com/mychore/mychore_server/dto/chore/request/ChoreCreateReq.java
  src/main/java/com/mychore/mychore_server/dto/chore/request/ChoreUpdateReq.java
  src/main/java/com/mychore/mychore_server/dto/chore/response/ChoreDetailResp.java
  src/main/java/com/mychore/mychore_server/dto/chore/response/ChoreSimpleResp.java
  src/main/java/com/mychore/mychore_server/entity/chore/Chore.java
  src/main/java/com/mychore/mychore_server/entity/chore/ChoreLog.java
  src/main/java/com/mychore/mychore_server/exception/chore/ChoreBadRequestException.java
  src/main/java/com/mychore/mychore_server/exception/chore/ChoreExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/chore/ChoreNotFoundException.java
  src/main/java/com/mychore/mychore_server/repository/ChoreLogRepository.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepository.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepositoryCustom.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepositoryCustomImpl.java
  src/main/java/com/mychore/mychore_server/repository/GroupRepository.java
  src/main/java/com/mychore/mychore_server/repository/GroupUserRepository.java
  src/main/java/com/mychore/mychore_server/repository/RoomFurnitureRepository.java
  src/main/java/com/mychore/mychore_server/repository/RoomRepository.java
  src/main/java/com/mychore/mychore_server/service/ChoreService.java
  src/main/resources/application.yaml
Labels: 🏡feature

#15 #10 그룹 관련 api
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/dto/Group/GroupAssembler.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/AddFurnitureReqDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/FurnitureInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/RoomFurnitureInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/RoomInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/PostGroupReqDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/PostRoomReqDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/FurnitureResDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/PostGroupResDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/PostRoomResDTO.java
  src/main/java/com/mychore/mychore_server/entity/group/Furniture.java
  src/main/java/com/mychore/mychore_server/entity/group/Group.java
  src/main/java/com/mychore/mychore_server/entity/group/GroupUser.java
  src/main/java/com/mychore/mychore_server/entity/group/Room.java
  src/main/java/com/mychore/mychore_server/entity/group/RoomFurniture.java
  src/main/java/com/mychore/mychore_server/exception/group/FurnitureNotFoundException.java
  src/main/java/com/mychore/mychore_server/exception/group/GroupAlreadyExistException.java
  src/main/java/com/mychore/mychore_server/exception/group/GroupExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/group/GroupNotFoundException.java
  src/main/java/com/mychore/mychore_server/exception/group/InvalidInvitationCodeException.java
  src/main/java/com/mychore/mychore_server/exception/group/RoomNotFoundException.java
  src/main/java/com/mychore/mychore_server/global/constants/FurnitureType.java
  src/main/java/com/mychore/mychore_server/repository/FurnitureRepository.java
  src/main/java/com/mychore/mychore_server/repository/GroupRepository.java
  src/main/java/com/mychore/mychore_server/repository/GroupUserRepository.java
  src/main/java/com/mychore/mychore_server/repository/RoomFurnitureRepository.java
  src/main/java/com/mychore/mychore_server/repository/RoomRepository.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
Labels: 🏡feature

#25 #10 feat: 정적 데이터 조회
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/dto/Group/GroupAssembler.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/PlacedFurnitureInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/RoomInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/UserInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/FurnitureResDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/StaticDataResDTO.java
  src/main/java/com/mychore/mychore_server/exception/group/GroupExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/group/InvalidApproachException.java
  src/main/java/com/mychore/mychore_server/exception/group/InvalidTypeNameException.java
  src/main/java/com/mychore/mychore_server/global/constants/FurnitureType.java
  src/main/java/com/mychore/mychore_server/global/constants/RoomType.java
  src/main/java/com/mychore/mychore_server/repository/FurnitureRepository.java
  src/main/java/com/mychore/mychore_server/repository/GroupUserRepository.java
  src/main/java/com/mychore/mychore_server/repository/RoomFurnitureRepository.java
  src/main/java/com/mychore/mychore_server/repository/RoomRepository.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
Labels: 🏡feature

#28 Hotfix/26 test
  .github/workflows/deploy.yml
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
Labels: 🚑 hotfix

#30 #10 feat: 참여중인 그룹 리스트 조회 api
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/dto/Group/GroupAssembler.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/GroupListInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/UserInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/FurnitureResDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/StaticDataResDTO.java
  src/main/java/com/mychore/mychore_server/repository/GroupUserRepository.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
Labels: 🏡feature

#34 #9 feat: 집안일 완료율 조회 API
  src/main/java/com/mychore/mychore_server/controller/ChoreController.java
  src/main/java/com/mychore/mychore_server/service/ChoreService.java
Labels: 🏡feature

#37 Hotfix/26
  .github/workflows/deploy.yml
  .github/workflows/testDeploy.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/mychore/mychore_server/global/GloberController.java
Labels: 🚑 hotfix

#38 #36 feat: 토큰 재발급 API 생성
  src/main/java/com/mychore/mychore_server/controller/UserController.java
Labels: 🏡feature

#40 #23 feat: 프로필 이미지 수정, 삭제 API
  src/main/java/com/mychore/mychore_server/controller/UserController.java
  src/main/java/com/mychore/mychore_server/dto/Group/GroupAssembler.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/UserInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Req/PostGroupReqDTO.java
  src/main/java/com/mychore/mychore_server/dto/user/UserAssembler.java
  src/main/java/com/mychore/mychore_server/dto/user/request/UserSignUpReq.java
  src/main/java/com/mychore/mychore_server/dto/user/response/GetProfileRes.java
  src/main/java/com/mychore/mychore_server/entity/user/User.java
  src/main/java/com/mychore/mychore_server/global/constants/Constant.java
  src/main/java/com/mychore/mychore_server/global/exception/BaseResponseCode.java
  src/main/java/com/mychore/mychore_server/service/UserService.java
Labels: 🏡feature

#43 #10 refactor: getRoomChoreInfo api에서 잘못 설정된 exception 조건 수정
  src/main/java/com/mychore/mychore_server/service/GroupService.java
Labels: ♻️refactor

#44 #10 feat: delete member & refactor: exception handling
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/dto/Group/GroupAssembler.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/CheckResDTO.java
  src/main/java/com/mychore/mychore_server/global/exception/BaseResponseCode.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepository.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
Labels: 🏡feature, ♻️refactor

#47 #41 refactor: 집안일 조회 쿼리 최적화
  src/main/java/com/mychore/mychore_server/controller/ChoreController.java
  src/main/java/com/mychore/mychore_server/dto/chore/request/ChoreCreateReq.java
  src/main/java/com/mychore/mychore_server/dto/chore/response/ChoreDetailResp.java
  src/main/java/com/mychore/mychore_server/entity/chore/Chore.java
  src/main/java/com/mychore/mychore_server/global/constants/Repetition.java
  src/main/java/com/mychore/mychore_server/global/exception/BaseResponseCode.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepositoryCustom.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepositoryCustomImpl.java
  src/main/java/com/mychore/mychore_server/repository/GroupUserRepository.java
  src/main/java/com/mychore/mychore_server/service/ChoreService.java
Labels: ♻️refactor

#48 #45 feat: cascade 설정
  .gitignore
  src/main/java/com/mychore/mychore_server/entity/chore/Chore.java
  src/main/java/com/mychore/mychore_server/entity/chore/ChoreLog.java
  src/main/java/com/mychore/mychore_server/entity/group/Furniture.java
  src/main/java/com/mychore/mychore_server/entity/group/Group.java
  src/main/java/com/mychore/mychore_server/entity/group/GroupUser.java
  src/main/java/com/mychore/mychore_server/entity/group/Room.java
  src/main/java/com/mychore/mychore_server/entity/group/RoomFurniture.java
  src/main/java/com/mychore/mychore_server/entity/notification/Notification.java
  src/main/java/com/mychore/mychore_server/entity/user/User.java
  src/main/java/com/mychore/mychore_server/entity/user/UserAgree.java
  src/main/java/com/mychore/mychore_server/global/entityListener/ChoreEntityListener.java
  src/main/java/com/mychore/mychore_server/global/entityListener/GroupEntityListener.java
  src/main/java/com/mychore/mychore_server/global/entityListener/RoomEntityListener.java
  src/main/java/com/mychore/mychore_server/global/entityListener/UserEntityListener.java
  src/main/java/com/mychore/mychore_server/global/utils/BeanUtils.java
  src/main/java/com/mychore/mychore_server/repository/ChoreLogRepository.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepository.java
  src/main/java/com/mychore/mychore_server/repository/GroupRepository.java
  src/main/java/com/mychore/mychore_server/repository/GroupUserRepository.java
  src/main/java/com/mychore/mychore_server/repository/NotificationRepository.java
  src/main/java/com/mychore/mychore_server/repository/RoomFurnitureRepository.java
  src/main/java/com/mychore/mychore_server/repository/RoomRepository.java
  src/main/java/com/mychore/mychore_server/repository/UserAgreeRepository.java
  src/main/java/com/mychore/mychore_server/service/UserService.java
Labels: 🏡feature

#51 #11 private key 이름 오류 해결
  src/main/java/com/mychore/mychore_server/service/NotificationService.java
Labels: 🔨fix

#49 #45 refactor: group user delete cascade 적용
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
Labels: ♻️refactor

#50 #10 feat: 그룹 삭제 api
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
Labels: 🏡feature

#53 #52 refactor: date response type 변경
  src/main/java/com/mychore/mychore_server/dto/Group/Req/InfoList/GroupListInfoDTO.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/StaticDataResDTO.java
Labels: ♻️refactor

#55 #54 feat: remain chore counter api
  src/main/java/com/mychore/mychore_server/controller/ChoreController.java
  src/main/java/com/mychore/mychore_server/dto/Group/GroupAssembler.java
  src/main/java/com/mychore/mychore_server/dto/Group/Res/RoomChoreResDTO.java
  src/main/java/com/mychore/mychore_server/dto/chore/ChoreAssembler.java
  src/main/java/com/mychore/mychore_server/dto/chore/response/RemainChoreResDTO.java
  src/main/java/com/mychore/mychore_server/service/ChoreService.java
Labels: 🏡feature

#56 #45 feat: groupUser cascade 설정 추가
  src/main/java/com/mychore/mychore_server/entity/group/GroupUser.java
  src/main/java/com/mychore/mychore_server/global/entityListener/GroupUserEntityListener.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepository.java
Labels: 🏡feature

#57 #11 그룹원 추가, 그룹 삭제 알림 기능 연결
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
  src/main/java/com/mychore/mychore_server/service/NotificationService.java
Labels: 🏡feature

#62 #61 refactor: room 정보가 null인 경우도 처리하도록 수정
  src/main/java/com/mychore/mychore_server/dto/Group/Req/PostGroupReqDTO.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
Labels: ♻️refactor

#60 #11 user부분 deviceToken 추가
  src/main/java/com/mychore/mychore_server/dto/user/UserAssembler.java
  src/main/java/com/mychore/mychore_server/dto/user/request/UserLogInReq.java
  src/main/java/com/mychore/mychore_server/dto/user/request/UserSignUpReq.java
  src/main/java/com/mychore/mychore_server/entity/user/User.java
  src/main/java/com/mychore/mychore_server/service/NotificationService.java
  src/main/java/com/mychore/mychore_server/service/UserService.java
Labels: 🏡feature
