Repository MyChore/MyChore-Server, pull requests merged in 2023-07, with the labels that each got.

#2 #1 프로젝트 초기 설정
  src/main/java/com/mychore/mychore_server/constant/FloorType.java
  src/main/java/com/mychore/mychore_server/constant/Provider.java
  src/main/java/com/mychore/mychore_server/constant/Repetition.java
  src/main/java/com/mychore/mychore_server/constant/Role.java
  src/main/java/com/mychore/mychore_server/constant/RoomType.java
  src/main/java/com/mychore/mychore_server/controller/CalendarController.java
  src/main/java/com/mychore/mychore_server/controller/ChoreController.java
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/controller/NotificationController.java
  src/main/java/com/mychore/mychore_server/controller/UserController.java
  src/main/java/com/mychore/mychore_server/entity/BaseEntity.java
  src/main/java/com/mychore/mychore_server/entity/chore/Chore.java
  src/main/java/com/mychore/mychore_server/entity/chore/ChoreLog.java
  src/main/java/com/mychore/mychore_server/entity/group/Furniture.java
  src/main/java/com/mychore/mychore_server/entity/group/Group.java
  src/main/java/com/mychore/mychore_server/entity/group/GroupUser.java
  src/main/java/com/mychore/mychore_server/entity/group/Room.java
  src/main/java/com/mychore/mychore_server/entity/group/RoomFurniture.java
  src/main/java/com/mychore/mychore_server/entity/notification/Notification.java
  src/main/java/com/mychore/mychore_server/entity/user/User.java
  src/main/java/com/mychore/mychore_server/entity/user/UserAgree.java
  src/main/java/com/mychore/mychore_server/repository/ChoreRepository.java
  src/main/java/com/mychore/mychore_server/repository/GroupRepository.java
  src/main/java/com/mychore/mychore_server/repository/NotificationRepository.java
  src/main/java/com/mychore/mychore_server/repository/UserRepository.java
  src/main/java/com/mychore/mychore_server/service/ChoreService.java
  src/main/java/com/mychore/mychore_server/service/GroupService.java
  src/main/java/com/mychore/mychore_server/service/NotificationService.java
  src/main/java/com/mychore/mychore_server/service/UserService.java
Labels: 🌏infra, 🏡feature

#3 #1 response 틀 및 exception 틀 생성
  src/main/java/com/mychore/mychore_server/constant/Provider.java
  src/main/java/com/mychore/mychore_server/constant/Role.java
  src/main/java/com/mychore/mychore_server/controller/CalendarController.java
  src/main/java/com/mychore/mychore_server/controller/ChoreController.java
  src/main/java/com/mychore/mychore_server/controller/GroupController.java
  src/main/java/com/mychore/mychore_server/controller/NotificationController.java
  src/main/java/com/mychore/mychore_server/controller/TestController.java
  src/main/java/com/mychore/mychore_server/controller/UserController.java
  src/main/java/com/mychore/mychore_server/dto/ResponseCustom.java
  src/main/java/com/mychore/mychore_server/entity/chore/Chore.java
  src/main/java/com/mychore/mychore_server/entity/group/Group.java
  src/main/java/com/mychore/mychore_server/entity/group/GroupUser.java
  src/main/java/com/mychore/mychore_server/entity/group/Room.java
  src/main/java/com/mychore/mychore_server/entity/user/User.java
  src/main/java/com/mychore/mychore_server/exception/chore/ChoreExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/group/GroupExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/notification/NotificationExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/user/UserExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/user/UserNotFoundException.java
  src/main/java/com/mychore/mychore_server/global/constants/Constant.java
  src/main/java/com/mychore/mychore_server/global/constants/FloorType.java
  src/main/java/com/mychore/mychore_server/global/constants/Provider.java
  src/main/java/com/mychore/mychore_server/global/constants/Repetition.java
  src/main/java/com/mychore/mychore_server/global/constants/Role.java
  src/main/java/com/mychore/mychore_server/global/constants/RoomType.java
Labels: 🌏infra, 🏡feature

#8 #7 refactor: DB 수정 및 CalendarController 삭제
  src/main/java/com/mychore/mychore_server/controller/CalendarController.java
  src/main/java/com/mychore/mychore_server/entity/chore/Chore.java
  src/main/java/com/mychore/mychore_server/entity/chore/ChoreLog.java
  src/main/java/com/mychore/mychore_server/entity/group/Furniture.java
  src/main/java/com/mychore/mychore_server/entity/group/Group.java
  src/main/java/com/mychore/mychore_server/entity/group/GroupUser.java
  src/main/java/com/mychore/mychore_server/entity/group/Room.java
  src/main/java/com/mychore/mychore_server/entity/group/RoomFurniture.java
  src/main/java/com/mychore/mychore_server/entity/notification/Notification.java
  src/main/java/com/mychore/mychore_server/entity/user/User.java
  src/main/java/com/mychore/mychore_server/entity/user/UserAgree.java
  src/main/java/com/mychore/mychore_server/global/constants/FloorType.java
  src/main/java/com/mychore/mychore_server/global/constants/Provider.java
  src/main/java/com/mychore/mychore_server/global/constants/Repetition.java
  src/main/java/com/mychore/mychore_server/global/constants/Role.java
  src/main/java/com/mychore/mychore_server/global/constants/RoomType.java
Labels: ♻️refactor, 🔨fix

#12 #6 회원가입, 로그인, 프로필 수정 API 생성
  build.gradle
  src/main/java/com/mychore/mychore_server/MyChoreServerApplication.java
  src/main/java/com/mychore/mychore_server/controller/TestController.java
  src/main/java/com/mychore/mychore_server/controller/UserController.java
  src/main/java/com/mychore/mychore_server/dto/user/UserAssembler.java
  src/main/java/com/mychore/mychore_server/dto/user/request/PatchProfileReq.java
  src/main/java/com/mychore/mychore_server/dto/user/request/UserLogInReq.java
  src/main/java/com/mychore/mychore_server/dto/user/request/UserSignUpReq.java
  src/main/java/com/mychore/mychore_server/dto/user/response/UserTokenRes.java
  src/main/java/com/mychore/mychore_server/entity/user/User.java
  src/main/java/com/mychore/mychore_server/entity/user/UserAgree.java
  src/main/java/com/mychore/mychore_server/exception/GlobalExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/user/AuthAnnotationIsNowhereException.java
  src/main/java/com/mychore/mychore_server/exception/user/EmailAlreadyExistException.java
  src/main/java/com/mychore/mychore_server/exception/user/EmailNotExistException.java
  src/main/java/com/mychore/mychore_server/exception/user/InvalidNicknameException.java
  src/main/java/com/mychore/mychore_server/exception/user/NicknameAlreadyExistException.java
  src/main/java/com/mychore/mychore_server/exception/user/TokenExpirationException.java
  src/main/java/com/mychore/mychore_server/exception/user/UserExceptionController.java
  src/main/java/com/mychore/mychore_server/exception/user/WrongGenderException.java
  src/main/java/com/mychore/mychore_server/exception/user/WrongProviderException.java
  src/main/java/com/mychore/mychore_server/global/config/WebConfig.java
  src/main/java/com/mychore/mychore_server/global/constants/Constant.java
  src/main/java/com/mychore/mychore_server/global/constants/FloorType.java
  src/main/java/com/mychore/mychore_server/global/constants/Gender.java
  src/main/java/com/mychore/mychore_server/global/constants/Provider.java
  src/main/java/com/mychore/mychore_server/global/constants/Repetition.java
  src/main/java/com/mychore/mychore_server/global/resolver/Auth.java
  src/main/java/com/mychore/mychore_server/global/resolver/IsLogin.java
  src/main/java/com/mychore/mychore_server/global/resolver/LoginResolver.java
  src/main/java/com/mychore/mychore_server/global/resolver/LoginStatus.java
  src/main/java/com/mychore/mychore_server/global/utils/JwtUtils.java
  src/main/java/com/mychore/mychore_server/repository/UserAgreeRepository.java
  src/main/java/com/mychore/mychore_server/repository/UserRepository.java
  src/main/java/com/mychore/mychore_server/service/UserService.java
  src/main/resources/application.yaml
  src/test/java/com/mychore/mychore_server/MyChoreServerApplicationTests.java
Labels: 🏡feature
